apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: hotel-booking
type: Opaque
stringData:
  JWT_SECRET_KEY: "my_super_jwt_secret_key_123"
  JWT_REFRESH_TOKEN_SECRET_KEY: "my_super_refresh_secret_key_123"
